Credit and Person now uses SQL.
Nicklason/SDU-2-semester-SE9 pull request #24
Opened 2020-05-05 12:12 UTC by Benji703

2020-05-05 13:00 UTC, Nicklason requested changes
Vi skal gå væk fra at gemme det i hukommelsen og i stedet for gøre så alle funktionerne i persistens interface får data direkte fra databasen, i stedet for at det hele bliver gemt i hukommelsen af programmet. Det er ikke særligt smart at indlæse hele databasen og så gemme det i hukommelsen. Det samme kan siges om at læse og skrive til file, men med en database er det meget nemmere at gøre det "rigtigt".

Den måde det skal laves på i stedet, er at programmet skal spørge databasen om data når det skal bruges, og på samme måde sende kun det nye som skal indsættes til databasen.

2020-05-06 18:11 UTC, Hicmu123 approved these changes

2020-05-06 18:46 UTC, Nicklason requested changes
I har formået at gøre det muligt at lave SQL injections.

I ignorerer også rigtigt mange SQLException fejl, hvilket gør at der kan komme rigtigt mange andre fejl.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            System.out.println(i);
Burde fjernes

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            }
Måden i gør det på er ikke så god fordi det er svært at læse. I sætter i til at være 0, hvor i så sætter det returnerede id fra jeres statement, det fungerer sikkert fint, men det er mærkeligt at læse. Måden jeg har gjort det på er stort set den samme måde https://github.com/Nicklason/SDU-2-semester-SE9/blob/eee18b3ac52710aa1c110953ef0e60fcd182a67e/src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceProgram.java#L36-L51

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +                returnValue.add(new Credit(result.getInt(1), result.getInt(2), result.getInt(3), result.getString(4)));
Brug navnet på kolonnerne i stedet for index for kolonnen. Hvis af en eller anden grund id ikke er det første i tabellen så kommer der til at ske en fejl, så for at sørge for at det ikke skulle ske så brug i stedet navnet på kolonnen:

```java
new Credit(result.getInt("id"), result.getInt("programID"), result.getInt("personID"), result.getString("role"));
```

Koden over virker sikkert ikke, men det er et eksempel på hvordan i skal gøre det.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM Credit WHERE programID =" + programID);
Dette er præcist hvad man aldrig må gøre. I skal bruge prepareStatement ordenligt, og det gøres ved at skrive `programID = ?` i stedet for at tilføje det direkte til strengen, og så bruge `stmt.setInt(1, programID)` for at sætte værdien. Hvis i ikke gør det, så kan i komme til at åbne databasen op for SQL injections.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            System.out.println(result);
Burde fjernes

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +                returnValue.add(new Credit(result.getInt(1), result.getInt(2), result.getInt(3), result.getString(4)));
Brug navne på kolonnerne

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM Credit WHERE programID ='" + programID + "' AND personID ='" + personID + "'");
Samme problem som før, mulig SQL injection...

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = PersistenceDatabaseHelper.getConnection().prepareStatement("SELECT * FROM Credit WHERE programID ='" + programID + "' AND personID ='" + personID + "'" +
Mulig SQL injection...

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = PersistenceDatabaseHelper.getConnection().prepareStatement("SELECT * FROM Credit WHERE programID ='" + programID + "' AND roleName ='" + roleName + "'");
Mulig SQL injection...

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM Credit WHERE personID =" + personID);
SQL injection...

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM Credit WHERE personID =" + personID);
Brug i stedet LIMIT = ? og sæt det til at være maxCount. Hvis i ikke gør det så fortæller i databasen at den skal finde alle krediteringerne for personen, også i selv om man kun leder efter et specifikt antal.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            System.out.println(result);
Burde fjernes

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceDatabaseHelper.java
> +                    "last_name varchar(20) NOT NULL" +
I følger ikke design modellen for databasen, det hedder firstName og lastName, ikke first_name og last_name.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistencePerson.java
> +            System.out.println(i);
Burde fjernes

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistencePerson.java
> +            }
Samme som før, se hvordan jeg har gjort det: https://github.com/Nicklason/SDU-2-semester-SE9/blob/eee18b3ac52710aa1c110953ef0e60fcd182a67e/src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceProgram.java#L36-L51

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistencePerson.java
> +            String lastName = rs.getString("last_name");
skal ændres når i også ændre navnene på kolonnerne i databasen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistencePerson.java
> +            PreparedStatement stmt = connection.prepareStatement("SELECT * FROM person WHERE first_name ='" + firstName + "' AND last_name ='" + lastName+"'");
SQL injection. Dette kan rent faktisk bruges til at få fuld adgang til databasen, hvilket betyder man kan få og redigerer alt data, og f.eks. også slette hele databasen. Det kan man her fordi der er det strenge som brugeren selv skriver ind, og man kan derfor til f.eks. efternavnet skrive noget som "\"DROP TABLE...'" for at slette tabeller i databasen.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/ExportController.java
> +            //Alert user of exception
hvis der sker en fejl så skal funktionen stoppe, den skal ikke fortsætte. Hvis den fortsætter så kan der ske fejl.

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/ExportController.java
> +            }
Stop funktion i stedet for at ignorerer fejlen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/InsertCreditsController.java
> +        }
Stop funktion i stedet for at ignorerer fejlen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/InsertCreditsController.java
> +        }
Stop funktion i stedet for at ignorerer fejlen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/InsertCreditsController.java
> +            //Alert user of exception
Stop funktion i stedet for at ignorerer fejlen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/InsertCreditsController.java
> +        }
Stop funktion i stedet for at ignorerer fejlen

2020-05-06 18:46 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/presentation/InsertCreditsController.java
> +        }
Stop funktion i stedet for at ignorerer fejlen

2020-05-07 12:52 UTC, Nicklason approved these changes

2020-05-07 12:52 UTC, Nicklason commented on src/main/java/sdu/se9/tv2/management/system/persistence/PersistenceCredit.java
> +            System.out.println(result);
Burde fjernes

2020-05-07 12:52 UTC, merged